import { bootstrapApplication } from '@angular/platform-browser';
import { importProvidersFrom } from '@angular/core';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { provideRouter } from '@angular/router';
import { provideAnimations } from '@angular/platform-browser/animations';
import {
  Activity,
  Archive,
  ArchiveRestore,
  ArrowLeft,
  BadgeCheck,
  Bell,
  Bold,
  Building2,
  CalendarDays,
  Clock,
  CircleAlert,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ClipboardList,
  Copy,
  DraftingCompass,
  FileCheck2,
  FilePenLine,
  FileType,
  FileText,
  Flag,
  Folder,
  FolderInput,
  FolderPen,
  FolderPlus,
  Hammer,
  Handshake,
  History,
  Image,
  Info,
  KeyRound,
  LayoutDashboard,
  Layers3,
  Link,
  List,
  ListChecks,
  LogIn,
  LogOut,
  Mail,
  MailCheck,
  MessageSquare,
  Menu,
  Moon,
  Pencil,
  Plus,
  Search,
  Save,
  Send,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Trash2,
  Upload,
  Download,
  Eye,
  UserCog,
  UserMinus,
  UserPlus,
  Users,
  Workflow,
  X,
  LucideAngularModule
} from 'lucide-angular';
import { AppComponent } from './app/app.component';
import { routes } from './app/app.routes';
import { authInterceptor } from './app/core/interceptors/auth.interceptor';

bootstrapApplication(AppComponent, {
  providers: [
    provideRouter(routes),
    provideHttpClient(withInterceptors([authInterceptor])),
    provideAnimations(),
    importProvidersFrom(LucideAngularModule.pick({
      Activity,
      Archive,
      ArchiveRestore,
      ArrowLeft,
      BadgeCheck,
      Bell,
      Bold,
      Building2,
      CalendarDays,
      Clock,
      CircleAlert,
      Check,
      CheckCircle2,
      ChevronDown,
      ChevronLeft,
      ChevronRight,
      ChevronUp,
      ClipboardList,
      Copy,
      DraftingCompass,
      FileCheck2,
      FilePenLine,
      FileType,
      FileText,
      Flag,
      Folder,
      FolderInput,
      FolderPen,
      FolderPlus,
      Hammer,
      Handshake,
      History,
      Image,
      Info,
      KeyRound,
      LayoutDashboard,
      Layers3,
      Link,
      List,
      ListChecks,
      LogIn,
      LogOut,
      Mail,
      MailCheck,
      MessageSquare,
      Menu,
      Moon,
      Pencil,
      Plus,
      Search,
      Save,
      Send,
      Settings,
      ShieldCheck,
      SlidersHorizontal,
      Sparkles,
      Sun,
      Trash2,
      Upload,
      Download,
      Eye,
      UserCog,
      UserMinus,
      UserPlus,
      Users,
      Workflow,
      X,
      'building-2': Building2,
      'calendar-days': CalendarDays,
      'chevron-left': ChevronLeft,
      'chevron-right': ChevronRight,
      'chevron-up': ChevronUp,
      'clipboard-list': ClipboardList,
      'file-text': FileText,
      'file-check-2': FileCheck2,
      'list-checks': ListChecks,
      'drafting-compass': DraftingCompass,
      folder: Folder,
      'folder-plus': FolderPlus,
      flag: Flag,
      hammer: Hammer,
      layers3: Layers3,
      users: Users
    }))
  ]
}).catch((err) => console.error(err));
