package com.arqly.backend.entity;

public enum ActivityType {
    COMMENT,
    STATUS_CHANGED,
    CHECKLIST_UPDATED,
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_COMPLETED,
    PHASE_CREATED,
    PHASE_UPDATED,
    STAGE_CREATED,
    STAGE_UPDATED,
    STAGE_COMPLETED,
    ASSIGNED,
    UNASSIGNED,
    FILE_UPLOADED,
    FILE_VERSIONED,
    FILE_DOWNLOADED,
    FILE_ARCHIVED,
    FILE_RESTORED,
    FILE_MOVED,
    FILE_RENAMED,
    DOCUMENT_GENERATED,
    CLIENT_APPROVAL,
    VISIT_REGISTERED,
    SYSTEM
}
