package com.arqly.backend.entity;
public enum NotificationSourceType { PROJECT, PROJECT_STAGE, ACTIVITY, APPROVAL, CALENDAR_EVENT, CONSTRUCTION_DIARY, DIARY_OCCURRENCE, FILE, DOCUMENT, FINANCIAL, TASK, PROPOSAL, BRIEFING }
