package com.arqly.backend.controller;
import com.arqly.backend.dto.ApiResponse; import com.arqly.backend.dto.FinancialDtos.*; import com.arqly.backend.entity.FinancialEntryType; import com.arqly.backend.security.AuthenticatedUser; import com.arqly.backend.service.FinancialService; import com.arqly.backend.service.FinancialQueryService; import com.arqly.backend.service.ProposalFinancialConversionService; import jakarta.validation.Valid; import java.util.*; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/financial") public class FinancialController {
 private final FinancialService service; private final ProposalFinancialConversionService conversion; private final FinancialQueryService queries;
 public FinancialController(FinancialService service,ProposalFinancialConversionService conversion,FinancialQueryService queries){this.service=service;this.conversion=conversion;this.queries=queries;}
 @GetMapping("/entries") public ApiResponse<List<EntryResponse>> list(@AuthenticationPrincipal AuthenticatedUser u,@RequestParam(required=false) FinancialEntryType type){return ApiResponse.ok(service.list(u.getTenantId(),type));}
 @GetMapping("/entries/{id}") public ApiResponse<EntryResponse> get(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable UUID id){return ApiResponse.ok(service.get(u.getTenantId(),id));}
 @GetMapping("/proposals/{id}/preview") public ApiResponse<ProposalFinancialPreview> preview(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable UUID id){return ApiResponse.ok(conversion.preview(u.getTenantId(),id));}
 @PostMapping("/proposals/{id}/generate") public ApiResponse<EntryResponse> generate(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable UUID id){return ApiResponse.ok(conversion.convert(u.getTenantId(),u.getId(),id));}
 @PostMapping("/entries") public ApiResponse<EntryResponse> create(@AuthenticationPrincipal AuthenticatedUser u,@Valid @RequestBody EntryRequest r){return ApiResponse.ok(service.create(u.getTenantId(),u.getId(),r));}
 @PostMapping("/entries/{id}/cancel") public ApiResponse<Void> cancel(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable UUID id){service.cancel(u.getTenantId(),u.getId(),id);return ApiResponse.message("Lançamento cancelado.");}
 @PostMapping("/installments/{id}/settlements") public ApiResponse<SettlementResponse> settle(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable UUID id,@Valid @RequestBody SettlementRequest r){return ApiResponse.ok(service.settle(u.getTenantId(),u.getId(),id,r));}
 @PostMapping("/settlements/{id}/reverse") public ApiResponse<Void> reverse(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable UUID id,@RequestBody(required=false) Map<String,String> b){service.reverse(u.getTenantId(),u.getId(),id,b==null?null:b.get("reason"));return ApiResponse.message("Liquidação estornada.");}
 @GetMapping("/cash-flow") public ApiResponse<CashFlowResponse> cash(@AuthenticationPrincipal AuthenticatedUser u){return ApiResponse.ok(service.cashFlow(u.getTenantId()));}
 @GetMapping("/projects/{id}/summary") public ApiResponse<ProjectFinancialSummary> project(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable UUID id){return ApiResponse.ok(queries.project(u.getTenantId(),id));}
 @GetMapping("/clients/{id}/summary") public ApiResponse<ClientFinancialSummary> client(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable UUID id){return ApiResponse.ok(queries.client(u.getTenantId(),id));}
 @GetMapping("/categories") public ApiResponse<List<CategoryResponse>> categories(@AuthenticationPrincipal AuthenticatedUser u){return ApiResponse.ok(service.categories(u.getTenantId()));}
 @PostMapping("/categories") public ApiResponse<CategoryResponse> category(@AuthenticationPrincipal AuthenticatedUser u,@Valid @RequestBody CategoryRequest r){return ApiResponse.ok(service.category(u.getTenantId(),u.getId(),r));}
}
